import type {
  Book,
  Hadith,
  HadithAssessment,
  Narrator,
  NarratorAssessment,
  Scholar,
  SourceVariationDetail,
} from "@/lib/types";

const scholarYahya: Scholar = {
  id: 1,
  slug: "yahya-ibn-main",
  name: "Yahya ibn Ma'in",
  arabic_name: "يحيى بن معين",
  tradition: "Sunni",
  birth_year_ah: null,
  death_year_ah: 233,
  credentials: "Early specialist in narrator criticism.",
  methodology: null,
};

const scholarBukhari: Scholar = {
  id: 3,
  slug: "al-bukhari",
  name: "Muhammad al-Bukhari",
  arabic_name: "محمد البخاري",
  tradition: "Sunni",
  birth_year_ah: null,
  death_year_ah: 256,
  credentials: "Hadith compiler and biographical critic.",
  methodology: null,
};

const scholarIbnHajar: Scholar = {
  id: 7,
  slug: "ibn-hajar",
  name: "Ibn Hajar al-Asqalani",
  arabic_name: "ابن حجر العسقلاني",
  tradition: "Sunni",
  birth_year_ah: null,
  death_year_ah: 852,
  credentials: "Hadith master and author of major narrator reference works.",
  methodology: null,
};

export const FALLBACK_SCHOLARS: Scholar[] = [scholarYahya, scholarBukhari, scholarIbnHajar];

export const FALLBACK_BOOKS: Book[] = [
  {
    id: 1,
    title: "Sahih al-Bukhari",
    arabic_title: "صحيح البخاري",
    author: "Muhammad al-Bukhari",
    tradition: "Sunni",
    book_type: "hadith_collection",
    source_url: "https://sunnah.com/bukhari",
    license: null,
  },
  {
    id: 2,
    title: "Sahih Muslim",
    arabic_title: "صحيح مسلم",
    author: "Muslim ibn al-Hajjaj",
    tradition: "Sunni",
    book_type: "hadith_collection",
    source_url: "https://sunnah.com/muslim",
    license: null,
  },
  {
    id: 3,
    title: "Al-Kafi",
    arabic_title: "الكافي",
    author: "Muhammad ibn Ya'qub al-Kulayni",
    tradition: "Twelver Shia",
    book_type: "hadith_collection",
    source_url: "https://thaqalayn.net/book/1",
    license: null,
  },
  {
    id: 4,
    title: "Nahj al-Balagha",
    arabic_title: "نهج البلاغة",
    author: "Al-Sharif al-Radi",
    tradition: "Twelver Shia",
    book_type: "hadith_collection",
    source_url: "https://thaqalayn.net/book/21",
    license: null,
  },
  {
    id: 5,
    title: "HadeethEnc Prophetic Encyclopedia",
    arabic_title: "موسوعة الأحاديث النبوية",
    author: "HadeethEnc Team",
    tradition: "Sunni",
    book_type: "commentary",
    source_url: "https://hadeethenc.com/en/home",
    license: null,
  },
];

export const FALLBACK_NARRATORS: Narrator[] = [
  {
    id: 1,
    slug: "umar-ibn-al-khattab",
    name: "Umar ibn al-Khattab",
    arabic_name: "عمر بن الخطاب",
    alternative_names: ["Umar"],
    birth_year_ah: null,
    death_year_ah: 23,
    region: "Medina",
    generation: "Companion",
    biography: "Second caliph and a major Companion narrator.",
    summary_score: null,
    identity_status: "verified",
  },
  {
    id: 2,
    slug: "alqamah-ibn-waqqas",
    name: "Alqamah ibn Waqqas",
    arabic_name: "علقمة بن وقاص",
    alternative_names: [],
    birth_year_ah: null,
    death_year_ah: null,
    region: "Medina",
    generation: "Successor",
    biography: "Medinan transmitter of the intentions report.",
    summary_score: null,
    identity_status: "verified",
  },
  {
    id: 3,
    slug: "sahl-ibn-sad",
    name: "Sahl ibn Sa'd",
    arabic_name: "سهل بن سعد",
    alternative_names: [],
    birth_year_ah: null,
    death_year_ah: 91,
    region: "Medina",
    generation: "Companion",
    biography: "Companion associated with the banner reports.",
    summary_score: null,
    identity_status: "verified",
  },
  {
    id: 4,
    slug: "abu-hurayra",
    name: "Abu Hurayra",
    arabic_name: "أبو هريرة",
    alternative_names: [],
    birth_year_ah: null,
    death_year_ah: 59,
    region: "Medina",
    generation: "Companion",
    biography: "Prolific Companion narrator.",
    summary_score: null,
    identity_status: "verified",
  },
];

export const FALLBACK_HADITHS: Array<Hadith & { variation_count: number }> = [
  {
    id: 5,
    slug: "first-revelation-at-hira",
    title: "The Beginning of Revelation (First Wahi at Cave Hira)",
    arabic_title: "بدء الوحي ونزول القرآن في غار حراء",
    summary: "Comprehensive cross-traditional parent cluster for the commencement of Divine Revelation to Prophet Muhammad (ﷺ) in the Cave of Hira, the descent of Gabriel with Surah al-Alaq (96:1-5), subsequent events with Khadijah and Waraqa ibn Nawfal, and cross-traditional accounts on certainty, tranquility, and early witnesses.",
    topics: ["revelation", "prophethood", "hira", "gabriel", "quran", "khadijah", "waraqa", "sakinah"],
    review_status: "published",
    variation_count: 6,
  },
  {
    id: 1,
    slug: "actions-by-intentions",
    title: "Actions are only by intentions",
    arabic_title: "إنما الأعمال بالنيات",
    summary: "Parent cluster for the famous intentions report. Each book occurrence keeps its own text and grades.",
    topics: ["intentions", "faith"],
    review_status: "published",
    variation_count: 2,
  },
  {
    id: 2,
    slug: "banner-at-khaybar",
    title: "Tomorrow I shall give the banner",
    arabic_title: "لأعطين الراية",
    summary: "Related banner accounts from Khaybar. Wording differs by source.",
    topics: ["virtues", "leadership"],
    review_status: "published",
    variation_count: 2,
  },
  {
    id: 3,
    slug: "best-manners",
    title: "The best among you are those with the best character",
    arabic_title: "إن من خياركم أحسنكم أخلاقا",
    summary: "Reports on manners and character, kept as separate source occurrences.",
    topics: ["character"],
    review_status: "published",
    variation_count: 1,
  },
  {
    id: 4,
    slug: "path-of-knowledge",
    title: "Whoever travels a path in search of knowledge",
    arabic_title: "من سلك طريقا يلتمس فيه علما",
    summary: "Knowledge reports with their own citations and chains.",
    topics: ["knowledge"],
    review_status: "published",
    variation_count: 1,
  },
];

function assessment(
  id: number,
  variationId: number,
  scholar: Scholar,
  original: string,
  explanation: string,
): HadithAssessment {
  return {
    id,
    variation_id: variationId,
    scholar_id: scholar.id,
    original_grade: original,
    normalized_grade: original.toLowerCase(),
    explanation,
    reference_book: scholar.name,
    edition: null,
    volume: null,
    page: null,
    source_url: null,
    verified: true,
    scholars: scholar,
  };
}

export const FALLBACK_VARIATIONS: Record<string, SourceVariationDetail[]> = {
  "first-revelation-at-hira": [
    {
      id: 51,
      hadith_id: 5,
      book_id: 1,
      hadith_number: "3",
      chapter: "Book of Revelation (كتاب بدء الوحي)",
      volume: "1",
      page: "2",
      arabic_text: "حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ، قَالَ: حَدَّثَنَا اللَّيْثُ، عَنْ عُقَيْلٍ، عَنِ ابْنِ شِهَابٍ، عَنْ عُرْوَةَ بْنِ الزُّبَيْرِ، عَنْ عَائِشَةَ أُمِّ الْمُؤْمِنِينَ أَنَّهَا قَالَتْ: أَوَّلُ مَا بُدِئَ بِهِ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِنَ الْوَحْيِ الرُّؤْيَا الصَّالِحَةُ فِي النَّوْمِ، فَكَانَ لاَ يَرَى رُؤْيَا إِلاَّ جَاءَتْ مِثْلَ فَلَقِ الصُّبْحِ، ثُمَّ حُبِّبَ إِلَيْهِ الْخَلاَءُ، وَكَانَ يَخْلُو بِغَارِ حِرَاءٍ فَيَتَحَنَّثُ فِيهِ ـ وَهُوَ التَّعَبُّدُ ـ اللَّيَالِيَ ذَوَاتِ الْعَدَدِ قَبْلَ أَنْ يَنْزِعَ إِلَى أَهْلِهِ، وَيَتَزَوَّدُ لِذَلِكَ، ثُمَّ يَرْجِعُ إِلَى خَدِيجَةَ فَيَتَزَوَّدُ لِمِثْلِهَا، حَتَّى جَاءَهُ الْحَقُّ وَهُوَ فِي غَارِ حِرَاءٍ، فَجَاءَهُ الْمَلَكُ فَقَالَ: اقْرَأْ. قَالَ: «مَا أَنَا بِقَارِئٍ». قَالَ: «فَأَخَذَنِي فَغَطَّنِي حَتَّى بَلَغَ مِنِّي الْجَهْدَ ثُمَّ أَرْسَلَنِي»، فَقَالَ: اقْرَأْ. قُلْتُ: «مَا أَنَا بِقَارِئٍ». فَأَخَذَنِي فَغَطَّنِي الثَّانِيَةَ حَتَّى بَلَغَ مِنِّي الْجَهْدَ ثُمَّ أَرْسَلَنِي، فَقَالَ: اقْرَأْ. فَقُلْتُ: «مَا أَنَا بِقَارِئٍ». فَأَخَذَنِي فَغَطَّنِي الثَّالِثَةَ ثُمَّ أَرْسَلَنِي، فَقَالَ: {اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ * خَلَقَ الإِنْسَانَ مِنْ عَلَقٍ * اقْرَأْ وَرَبُّكَ الأَكْرَمُ}. فَرَجَعَ بِهَا رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ يَرْجُفُ فُؤَادُهُ، فَدَخَلَ عَلَى خَدِيجَةَ بِنْتِ خُوَيْلِدٍ رَضِيَ اللَّهُ عَنْهَا فَقَالَ: «زَمِّلُونِي زَمِّلُونِي». فَزَمَّلُوهُ حَتَّى ذَهَبَ عَنْهُ الرَّوْعُ، فَقَالَ لِخَدِيجَةَ وَأَخْبَرَهَا الْخَبَرَ: «لَقَدْ خَشِيتُ عَلَى نَفْسِي». فَقَالَتْ خَدِيجَةُ: كَلاَّ وَاللَّهِ مَا يُخْزِيكَ اللَّهُ أَبَدًا، إِنَّكَ لَتَصِلُ الرَّحِمَ، وَتَحْمِلُ الْكَلَّ، وَتَكْسِبُ الْمَعْدُومَ، وَتَقْرِي الضَّيْفَ، وَتُعِينُ عَلَى نَوَائِبِ الْحَقِّ. فَانْطَلَقَتْ بِهِ خَدِيجَةُ حَتَّى أَتَتْ بِهِ وَرَقَةَ بْنَ نَوْفَلِ بْنِ أَسَدِ بْنِ عَبْدِ الْعُزَّى ابْنَ عَمِّ خَدِيجَةَ، وَكَانَ امْرَأً تَنَصَّرَ فِي الْجَاهِلِيَّةِ، وَكَانَ يَكْتُبُ الْكِتَابَ الْعِبْرَانِيَّ، فَيَكْتُبُ مِنَ الإِنْجِيلِ بِالْعِبْرَانِيَّةِ مَا شَاءَ اللَّهُ أَنْ يَكْتُبَ، وَكَانَ شَيْخًا كَبِيرًا قَدْ عَمِيَ، فَقَالَتْ لَهُ خَدِيجَةُ: يَا ابْنَ عَمِّ، اسْمَعْ مِنَ ابْنِ أَخِيكَ. فَقَالَ لَهُ وَرَقَةُ: يَا ابْنَ أَخِي مَاذَا تَرَى؟ فَأَخْبَرَهُ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ خَبَرَ مَا رَأَى. فَقَالَ لَهُ وَرَقَةُ: هَذَا النَّامُوسُ الَّذِي نَزَّلَ اللَّهُ عَلَى مُوسَى، يَا لَيْتَنِي فِيهَا جَذَعًا، لَيْتَنِي أَكُونُ حَيًّا إِذْ يُخْرِجُكَ قَوْمُكَ. فَقَالَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ: «أَوَمُخْرِجِيَّ هُمْ؟». قَالَ: نَعَمْ، لَمْ يَأْتِ رَجُلٌ قَطُّ بِمِثْلِ مَا جِئْتَ بِهِ إِلاَّ عُودِيَ، وَإِنْ يُدْرِكْنِي يَوْمُكَ أَنْصُرْكَ نَصْرًا مُؤَزَّرًا. ثُمَّ لَمْ يَنْشَبْ وَرَقَةُ أَنْ تُوُفِّيَ، وَفَتَرَ الْوَحْيُ.",
      english_text: "Narrated Aisha: The commencement of the Divine Inspiration to Allah's Messenger (ﷺ) was in the form of good righteous dreams in his sleep. He never had a dream but that it came true like bright daylight. He was also endowed with the love of seclusion, so he used to isolate himself in the cave of Hira, worshipping therein for a number of nights before coming back to his family to replenish his provisions. This continued until the Truth suddenly descended upon him while he was in the cave of Hira. The Angel came to him and said: 'Read!' He replied: 'I do not know how to read.' The Prophet added: 'The Angel seized me and squeezed me firmly until I could bear it no more, and then released me and said again: Read! I replied: I do not know how to read.' This was repeated three times, after which Gabriel recited the first verses of Surah al-Alaq (96:1-3). The Prophet returned to Khadijah trembling, and she comforted him and took him to Waraqah ibn Nawfal, who testified to the descent of the Divine Namus.",
      translator: "Dr. Muhammad Muhsin Khan",
      source_url: "https://sunnah.com/bukhari:3",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["marfu", "ahad", "first_wahi"],
      status_notes: "Canonical opening hadith of Sahih al-Bukhari on the commencement of revelation.",
      verified: true,
      books: FALLBACK_BOOKS[0],
      chains: [
        {
          id: 501,
          variation_id: 51,
          chain_number: 1,
          raw_chain_text: "Aisha ← Urwah ibn al-Zubayr ← Ibn Shihab al-Zuhri ← Uqayl ibn Khalid ← Al-Layth ibn Sa'd ← Yahya ibn Bukayr",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: "Primary canonical chain in Sahih al-Bukhari",
          verified: true,
          chain_narrators: [
            { id: 5001, chain_id: 501, narrator_id: 1, position: 1, raw_name: "Aisha bint Abi Bakr", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5002, chain_id: 501, narrator_id: 2, position: 2, raw_name: "Urwah ibn al-Zubayr", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5003, chain_id: 501, narrator_id: 3, position: 3, raw_name: "Ibn Shihab al-Zuhri", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5004, chain_id: 501, narrator_id: 4, position: 4, raw_name: "Uqayl ibn Khalid", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5005, chain_id: 501, narrator_id: 5, position: 5, raw_name: "Al-Layth ibn Sa'd", transmission_word: "haddathana", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5006, chain_id: 501, narrator_id: 6, position: 6, raw_name: "Yahya ibn Bukayr", transmission_word: "haddathana", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(501, 51, scholarBukhari, "Sahih", "Canonical opening of the Sahih."),
        assessment(502, 51, scholarIbnHajar, "Sahih", "Rigorous authentic report opening Kitab Bad' al-Wahy in Fath al-Bari."),
      ],
    },
    {
      id: 52,
      hadith_id: 5,
      book_id: 2,
      hadith_number: "160a",
      chapter: "Book of Faith (كتاب الإيمان)",
      volume: "1",
      page: "139",
      arabic_text: "حَدَّثَنِي أَبُو الطَّاهِرِ أَحْمَدُ بْنُ عَمْرِو بْنِ سَرْحٍ، حَدَّثَنَا ابْنُ وَهْبٍ، قَالَ: أَخْبَرَنِي يُونُسُ، عَنِ ابْنِ شِهَابٍ، قَالَ: حَدَّثَنِي عُرْوَةُ بْنُ الزُّبَيْرِ، أَنَّ عَائِشَةَ زَوْجَ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَخْبَرَتْهُ أَنَّهَا قَالَتْ: كَانَ أَوَّلَ مَا بُدِئَ بِهِ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِنَ الْوَحْيِ الرُّؤْيَا الصَّادِقَةُ فِي النَّوْمِ...",
      english_text: "Aisha reported: The beginning of Divine Revelation to the Messenger of Allah (ﷺ) was in the form of true dreams during sleep. He saw no dream but it came like the breaking of the dawn. Then seclusion was endeared to him in the Cave of Hira...",
      translator: "Abdul Hamid Siddiqui",
      source_url: "https://sunnah.com/muslim:160a",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["marfu", "ahad", "first_wahi"],
      status_notes: "Transmitted through Ibn Wahb and Yunus ibn Yazid from al-Zuhri.",
      verified: true,
      books: FALLBACK_BOOKS[1],
      chains: [],
      hadith_assessments: [
        assessment(503, 52, scholarBukhari, "Sahih", "Authentic narration recorded in Sahih Muslim."),
      ],
    },
    {
      id: 52,
      hadith_id: 5,
      book_id: 2,
      hadith_number: "160a",
      chapter: "Book of Faith (كتاب الإيمان)",
      volume: "1",
      page: "139",
      arabic_text: "حَدَّثَنِي أَبُو الطَّاهِرِ أَحْمَدُ بْنُ عَمْرِو بْنِ سَرْحٍ، حَدَّثَنَا ابْنُ وَهْبٍ، قَالَ: أَخْبَرَنِي يُونُسُ، عَنِ ابْنِ شِهَابٍ، قَالَ: حَدَّثَنِي عُرْوَةُ بْنُ الزُّبَيْرِ، أَنَّ عَائِشَةَ زَوْجَ النَّبِيِّ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ أَخْبَرَتْهُ أَنَّهَا قَالَتْ: كَانَ أَوَّلَ مَا بُدِئَ بِهِ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِنَ الْوَحْيِ الرُّؤْيَا الصَّادِقَةُ فِي النَّوْمِ...",
      english_text: "Aisha reported: The beginning of Divine Revelation to the Messenger of Allah (ﷺ) was in the form of true dreams during sleep. He saw no dream but it came like the breaking of the dawn. Then seclusion was endeared to him in the Cave of Hira...",
      translator: "Abdul Hamid Siddiqui",
      source_url: "https://sunnah.com/muslim:160a",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["marfu", "ahad", "first_wahi"],
      status_notes: "Transmitted through Ibn Wahb and Yunus ibn Yazid from al-Zuhri.",
      verified: true,
      books: FALLBACK_BOOKS[1],
      chains: [
        {
          id: 502,
          variation_id: 52,
          chain_number: 1,
          raw_chain_text: "Aisha ← Urwah ibn al-Zubayr ← Ibn Shihab al-Zuhri ← Yunus ibn Yazid ← Abd Allah ibn Wahb ← Abu al-Tahir",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: "Canonical Muslim isnad route via Ibn Wahb",
          verified: true,
          chain_narrators: [
            { id: 5010, chain_id: 502, narrator_id: 1, position: 1, raw_name: "Aisha bint Abi Bakr", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: FALLBACK_NARRATORS[0] },
            { id: 5011, chain_id: 502, narrator_id: 2, position: 2, raw_name: "Urwah ibn al-Zubayr", transmission_word: "haddathani", match_confidence: 1, match_notes: null, narrators: FALLBACK_NARRATORS[1] },
            { id: 5012, chain_id: 502, narrator_id: 3, position: 3, raw_name: "Ibn Shihab al-Zuhri", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5013, chain_id: 502, narrator_id: 7, position: 4, raw_name: "Yunus ibn Yazid al-Ayli", transmission_word: "akhbarani", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5014, chain_id: 502, narrator_id: 8, position: 5, raw_name: "Abd Allah ibn Wahb", transmission_word: "haddathana", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5015, chain_id: 502, narrator_id: 9, position: 6, raw_name: "Abu al-Tahir Ahmad ibn Amr", transmission_word: "haddathani", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(503, 52, scholarBukhari, "Sahih", "Authentic narration recorded in Sahih Muslim."),
      ],
    },
    {
      id: 53,
      hadith_id: 5,
      book_id: 1,
      hadith_number: "4",
      chapter: "Book of Revelation - Intermission (فترة الوحي)",
      volume: "1",
      page: "3",
      arabic_text: "حَدَّثَنَا يَحْيَى بْنُ بُكَيْرٍ، حَدَّثَنَا اللَّيْثُ، عَنْ عُقَيْلٍ، عَنِ ابْنِ شِهَابٍ، قَالَ: سَمِعْتُ أَبَا سَلَمَةَ بْنَ عَبْدِ الرَّحْمَنِ، يَقُولُ: أَخْبَرَنِي جَابِرُ بْنُ عَبْدِ اللَّهِ الأَنْصَارِيُّ، وَهُوَ يُحَدِّثُ عَنْ فَتْرَةِ الْوَحْيِ...",
      english_text: "Narrated Jabir ibn Abd Allah: The Prophet (ﷺ) said while speaking of the interval of revelation: 'While I was walking, I suddenly heard a voice from the sky. I looked up and saw the very same Angel who had visited me at Hira sitting on a chair between the sky and the earth...'",
      translator: "Dr. Muhammad Muhsin Khan",
      source_url: "https://sunnah.com/bukhari:4",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["marfu", "ahad", "first_wahi", "fatrat_al_wahy"],
      status_notes: "Narrates the resumption of revelation after the initial pause.",
      verified: true,
      books: FALLBACK_BOOKS[0],
      chains: [
        {
          id: 503,
          variation_id: 53,
          chain_number: 1,
          raw_chain_text: "Jabir ibn Abd Allah ← Abu Salama ibn Abd al-Rahman ← Ibn Shihab al-Zuhri ← Uqayl ibn Khalid ← Al-Layth ibn Sa'd ← Yahya ibn Bukayr",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: "Authentic Bukhari isnad on the interval of revelation",
          verified: true,
          chain_narrators: [
            { id: 5020, chain_id: 503, narrator_id: 10, position: 1, raw_name: "Jabir ibn Abd Allah al-Ansari", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5021, chain_id: 503, narrator_id: 11, position: 2, raw_name: "Abu Salama ibn Abd al-Rahman", transmission_word: "yagulu", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5022, chain_id: 503, narrator_id: 3, position: 3, raw_name: "Ibn Shihab al-Zuhri", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5023, chain_id: 503, narrator_id: 4, position: 4, raw_name: "Uqayl ibn Khalid", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5024, chain_id: 503, narrator_id: 5, position: 5, raw_name: "Al-Layth ibn Sa'd", transmission_word: "haddathana", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5025, chain_id: 503, narrator_id: 6, position: 6, raw_name: "Yahya ibn Bukayr", transmission_word: "haddathana", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(504, 53, scholarIbnHajar, "Sahih", "Resumption of revelation through Surah al-Muddaththir."),
      ],
    },
    {
      id: 54,
      hadith_id: 5,
      book_id: 3,
      hadith_number: "Vol 1 Book 4 Hadith 1129",
      chapter: "Book of Divine Proof (كتاب الحجة)",
      volume: "1",
      page: "176",
      arabic_text: "عَلِيُّ بْنُ إِبْرَاهِيمَ، عَنْ أَبِيهِ، عَنِ ابْنِ أَبِي عُمَيْرٍ، عَنْ هِشَامِ بْنِ سَالِمٍ، عَنْ زُرَارَةَ، قَالَ: قُلْتُ لِأَبِي عَبْدِ اللَّهِ (عَلَيْهِ السَّلَامُ): كَيْفَ لَمْ يَخَفْ رَسُولُ اللَّهِ (صَلَّى اللَّهُ عَلَيْهِ وَآلِهِ) فِيمَا يَأْتِيهِ مِنْ قِبَلِ اللَّهِ أَنْ يَكُونَ ذَلِكَ مِمَّا يَنْزَغُ بِهِ الشَّيْطَانُ؟ فَقَالَ: «إِنَّ اللَّهَ إِذَا اتَّخَذَ عَبْدًا رَسُولًا أَنْزَلَ عَلَيْهِ السَّكِينَةَ وَالْوَقَارَ، فَكَانَ يَأْتِيهِ مِنْ قِبَلِ اللَّهِ عَزَّ وَجَلَّ مِثْلَ الَّذِي يَرَاهُ بِعَيْنِهِ».",
      english_text: "Zurarah asked Imam Ja'far al-Sadiq: 'How was the Messenger of Allah immune from fearing that what came to him from Allah might be an evil prompting of Satan?' The Imam replied: 'Indeed, when Allah chooses a servant to be a Messenger, He descends upon him divine tranquility (al-Sakinah) and dignity (al-Waqar), so that what comes to him from Allah is as certain as that which he sees directly with his own eyes.'",
      translator: "Muhammad Sarwar / Sayyid Muhammad Rizvi",
      source_url: "https://thaqalayn.net/hadith/1/4/112/1",
      hadith_status: "muwaththaq",
      chain_status: "muttasil",
      narration_status: ["marfu", "ahad", "first_wahi", "theological_proof"],
      status_notes: "Twelver Shia foundational report establishing infallible certainty at the onset of revelation.",
      verified: true,
      books: FALLBACK_BOOKS[2],
      chains: [
        {
          id: 504,
          variation_id: 54,
          chain_number: 1,
          raw_chain_text: "Zurarah ← Hisham ibn Salim ← Ibn Abi Umayr ← Ali ibn Ibrahim's father ← Ali ibn Ibrahim",
          continuity_status: "muttasil",
          quality_status: "muwaththaq",
          notes: "Foundational Imami chain in Al-Kafi",
          verified: true,
          chain_narrators: [
            { id: 5030, chain_id: 504, narrator_id: 12, position: 1, raw_name: "Zurarah ibn A'yan", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5031, chain_id: 504, narrator_id: 13, position: 2, raw_name: "Hisham ibn Salim", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5032, chain_id: 504, narrator_id: 14, position: 3, raw_name: "Ibn Abi Umayr", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5033, chain_id: 504, narrator_id: 15, position: 4, raw_name: "Ibrahim ibn Hashim", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5034, chain_id: 504, narrator_id: 16, position: 5, raw_name: "Ali ibn Ibrahim al-Qummi", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(505, 54, scholarYahya, "Muwaththaq", "Graded as reliable like sahih in Mir'at al-Uqul."),
      ],
    },
    {
      id: 55,
      hadith_id: 5,
      book_id: 4,
      hadith_number: "Sermon 192",
      chapter: "The Sermon of Disparagement (الخطبة القاصعة)",
      volume: "1",
      page: "300",
      arabic_text: "قَالَ أَمِيرُ الْمُؤْمِنِينَ عَلِيُّ بْنُ أَبِي طَالِبٍ (عَلَيْهِ السَّلَامُ): «وَلَقَدْ كَانَ يُجَاوِرُ فِي كُلِّ سَنَةٍ بِحِرَاءَ فَأَرَاهُ وَلاَ يَرَاهُ غَيْرِي... أَرَى نُورَ الْوَحْيِ وَالرِّسَالَةِ، وَأَشُمُّ رِيحَ النُّبُوَّةِ، وَلَقَدْ سَمِعْتُ رَنَّةَ الشَّيْطَانِ حِينَ نَزَلَ الْوَحْيُ عَلَيْهِ صَلَّى اللَّهُ عَلَيْهِ وَآلِهِ...»",
      english_text: "Amir al-Mu'minin Ali ibn Abi Talib said: 'Every year the Messenger of Allah used to stay in seclusion at Mount Hira where I used to see him while no one else saw him... I used to see the radiant light of Divine Revelation and the Message, and I inhaled the fragrance of Prophethood. I heard the mournful cry of Satan when revelation first descended upon him...'",
      translator: "Sayyid Ali Rida",
      source_url: "https://thaqalayn.net/chapter/21/1/192",
      hadith_status: "mashhur",
      chain_status: "muttasil",
      narration_status: ["marfu", "khutbah", "eyewitness_account"],
      status_notes: "Eyewitness narration from Ali ibn Abi Talib regarding the first revelation at Hira.",
      verified: true,
      books: FALLBACK_BOOKS[3],
      chains: [
        {
          id: 505,
          variation_id: 55,
          chain_number: 1,
          raw_chain_text: "Ali ibn Abi Talib ← Al-Sharif al-Radi",
          continuity_status: "muttasil",
          quality_status: "mashhur",
          notes: "Historical sermon chain recorded in Nahj al-Balagha",
          verified: true,
          chain_narrators: [
            { id: 5040, chain_id: 505, narrator_id: 17, position: 1, raw_name: "Ali ibn Abi Talib", transmission_word: "gala", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5041, chain_id: 505, narrator_id: 18, position: 2, raw_name: "Al-Sharif al-Radi", transmission_word: "rawahu", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(506, 55, scholarYahya, "Mashhur", "Famous sermon recorded in Nahj al-Balagha."),
      ],
    },
    {
      id: 56,
      hadith_id: 5,
      book_id: 5,
      hadith_number: "3068",
      chapter: "General Hadith Encyclopedia - Revelation & Virtues",
      volume: "1",
      page: "1",
      arabic_text: "عَنْ عَائِشَةَ رَضِيَ اللَّهُ عَنْهَا: أَنَّ أَوَّلَ مَا بُدِئَ بِهِ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ مِنَ الْوَحْيِ الرُّؤْيَا الصَّالِحَةُ فِي النَّوْمِ... فَنَزَلَ عَلَيْهِ مَلَكُ الْوَحْيِ بِقَوْلِهِ تَعَالَى: {اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ}.",
      english_text: "Narrated by Aisha: The commencement of revelation began with righteous dreams during sleep. The Angel of Revelation descended in the Cave of Hira with Surat al-Alaq. Vocabulary analysis of Tahannuth, Falaq al-Subh, and al-Namus.",
      translator: "HadeethEnc Team",
      source_url: "https://hadeethenc.com/en/browse/hadith/3068",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["marfu", "pedagogical_explanation"],
      status_notes: "Pedagogical reference with vocabulary analysis.",
      verified: true,
      books: FALLBACK_BOOKS[4],
      chains: [
        {
          id: 506,
          variation_id: 56,
          chain_number: 1,
          raw_chain_text: "Aisha bint Abi Bakr ← HadeethEnc Editorial Board",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: "Pedagogical encyclopedic reference chain",
          verified: true,
          chain_narrators: [
            { id: 5050, chain_id: 506, narrator_id: 1, position: 1, raw_name: "Aisha bint Abi Bakr", transmission_word: "an", match_confidence: 1, match_notes: null, narrators: null },
            { id: 5051, chain_id: 506, narrator_id: 19, position: 2, raw_name: "HadeethEnc Scientific Committee", transmission_word: "haffazahu", match_confidence: 1, match_notes: null, narrators: null },
          ],
        },
      ],
      hadith_assessments: [
        assessment(507, 56, scholarIbnHajar, "Sahih", "HadeethEnc verified pedagogical entry."),
      ],
    },
  ],
  "actions-by-intentions": [
    {
      id: 11,
      hadith_id: 1,
      book_id: 1,
      hadith_number: "1",
      chapter: "Beginning of Revelation",
      volume: "1",
      page: "1",
      arabic_text: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
      english_text: "Actions are only by intentions, and each person will have only what they intended.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/bukhari:1",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: "Collection-level status for this Bukhari occurrence only.",
      verified: true,
      books: FALLBACK_BOOKS[0],
      chains: [
        {
          id: 101,
          variation_id: 11,
          chain_number: 1,
          raw_chain_text: "Umar ibn al-Khattab ← Alqamah ibn Waqqas",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 1001,
              chain_id: 101,
              narrator_id: 1,
              position: 1,
              raw_name: "Umar ibn al-Khattab",
              transmission_word: "an",
              match_confidence: 1,
              match_notes: null,
              narrators: FALLBACK_NARRATORS[0],
            },
            {
              id: 1002,
              chain_id: 101,
              narrator_id: 2,
              position: 2,
              raw_name: "Alqamah ibn Waqqas",
              transmission_word: "an",
              match_confidence: 1,
              match_notes: null,
              narrators: FALLBACK_NARRATORS[1],
            },
          ],
        },
      ],
      hadith_assessments: [
        assessment(201, 11, scholarBukhari, "Sahih", "Included in al-Sahih for this exact occurrence."),
        assessment(202, 11, scholarIbnHajar, "Sahih", "Later summary judgment attached to this Bukhari route."),
      ],
    },
    {
      id: 12,
      hadith_id: 1,
      book_id: 2,
      hadith_number: "1907",
      chapter: "On intention",
      volume: null,
      page: null,
      arabic_text: "إِنَّمَا الأَعْمَالُ بِالنِّيَّةِ",
      english_text: "Actions are only by intention.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/muslim:1907",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: "Grade belongs to this Muslim occurrence, not automatically to every variant.",
      verified: true,
      books: FALLBACK_BOOKS[1],
      chains: [
        {
          id: 102,
          variation_id: 12,
          chain_number: 1,
          raw_chain_text: "Umar ibn al-Khattab",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 1003,
              chain_id: 102,
              narrator_id: 1,
              position: 1,
              raw_name: "Umar ibn al-Khattab",
              transmission_word: "an",
              match_confidence: 1,
              match_notes: null,
              narrators: FALLBACK_NARRATORS[0],
            },
          ],
        },
      ],
      hadith_assessments: [assessment(203, 12, scholarBukhari, "Sahih", "Named for the Muslim occurrence.")],
    },
  ],
  "banner-at-khaybar": [
    {
      id: 21,
      hadith_id: 2,
      book_id: 1,
      hadith_number: "4210",
      chapter: "Military Expeditions",
      volume: null,
      page: null,
      arabic_text: "لَأُعْطِيَنَّ الرَّايَةَ غَدًا رَجُلًا يَفْتَحُ اللَّهُ عَلَى يَدَيْهِ",
      english_text: "Tomorrow I will give the banner to a man through whose hands God will grant victory.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/bukhari:4210",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: "Shown specifically for this Bukhari occurrence.",
      verified: true,
      books: FALLBACK_BOOKS[0],
      chains: [
        {
          id: 201,
          variation_id: 21,
          chain_number: 1,
          raw_chain_text: "Sahl ibn Sa'd",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 2001,
              chain_id: 201,
              narrator_id: 3,
              position: 1,
              raw_name: "Sahl ibn Sa'd",
              transmission_word: "an",
              match_confidence: 1,
              match_notes: null,
              narrators: FALLBACK_NARRATORS[2],
            },
          ],
        },
      ],
      hadith_assessments: [assessment(301, 21, scholarBukhari, "Sahih", "Collection-level status for this occurrence.")],
    },
    {
      id: 22,
      hadith_id: 2,
      book_id: 2,
      hadith_number: "2404",
      chapter: "Virtues of the Companions",
      volume: null,
      page: null,
      arabic_text: "لَأُعْطِيَنَّ الرَّايَةَ رَجُلًا يُحِبُّ اللَّهَ وَرَسُولَهُ",
      english_text: "I shall give the banner to a man who loves God and His Messenger.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/muslim:2404",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: "Different wording from the Bukhari occurrence in this cluster.",
      verified: true,
      books: FALLBACK_BOOKS[1],
      chains: [
        {
          id: 202,
          variation_id: 22,
          chain_number: 1,
          raw_chain_text: "Distinct Companion route",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 2002,
              chain_id: 202,
              narrator_id: 3,
              position: 1,
              raw_name: "Sahl ibn Sa'd",
              transmission_word: "an",
              match_confidence: 0.7,
              match_notes: "Review identity against the cited edition.",
              narrators: FALLBACK_NARRATORS[2],
            },
          ],
        },
      ],
      hadith_assessments: [assessment(302, 22, scholarIbnHajar, "Sahih", "Attributed to this Muslim occurrence.")],
    },
  ],
  "best-manners": [
    {
      id: 31,
      hadith_id: 3,
      book_id: 1,
      hadith_number: "3559",
      chapter: "Manners",
      volume: null,
      page: null,
      arabic_text: "إِنَّ مِنْ خِيَارِكُمْ أَحْسَنَكُمْ أَخْلَاقًا",
      english_text: "The best among you are those who have the best manners and character.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/bukhari:3559",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: null,
      verified: true,
      books: FALLBACK_BOOKS[0],
      chains: [
        {
          id: 301,
          variation_id: 31,
          chain_number: 1,
          raw_chain_text: "Abdullah ibn Amr route",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 3001,
              chain_id: 301,
              narrator_id: 4,
              position: 1,
              raw_name: "Abu Hurayra",
              transmission_word: "an",
              match_confidence: 0.5,
              match_notes: "Demo chain node for navigation.",
              narrators: FALLBACK_NARRATORS[3],
            },
          ],
        },
      ],
      hadith_assessments: [assessment(401, 31, scholarBukhari, "Sahih", "Named for this occurrence.")],
    },
  ],
  "path-of-knowledge": [
    {
      id: 41,
      hadith_id: 4,
      book_id: 2,
      hadith_number: "2699",
      chapter: "Knowledge",
      volume: null,
      page: null,
      arabic_text: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",
      english_text: "Whoever travels a path in search of knowledge, God makes easy for him a path to Paradise.",
      translator: "Illustrative English for demonstration",
      source_url: "https://sunnah.com/muslim:2699",
      hadith_status: "sahih",
      chain_status: "muttasil",
      narration_status: ["ahad", "marfu"],
      status_notes: null,
      verified: true,
      books: FALLBACK_BOOKS[1],
      chains: [
        {
          id: 401,
          variation_id: 41,
          chain_number: 1,
          raw_chain_text: "Abu Hurayra",
          continuity_status: "muttasil",
          quality_status: "sahih",
          notes: null,
          verified: true,
          chain_narrators: [
            {
              id: 4001,
              chain_id: 401,
              narrator_id: 4,
              position: 1,
              raw_name: "Abu Hurayra",
              transmission_word: "an",
              match_confidence: 1,
              match_notes: null,
              narrators: FALLBACK_NARRATORS[3],
            },
          ],
        },
      ],
      hadith_assessments: [assessment(501, 41, scholarIbnHajar, "Sahih", "Attributed judgment for this occurrence.")],
    },
  ],
};

export const FALLBACK_NARRATOR_ASSESSMENTS: Record<string, NarratorAssessment[]> = {
  "umar-ibn-al-khattab": [
    {
      id: 1,
      narrator_id: 1,
      scholar_id: scholarYahya.id,
      original_term: "ثقة",
      normalized_term: "thiqah",
      explanation: "Companion; reliability is discussed in rijal works with named attributions.",
      display_score: 95,
      mapping_method: "editorial display mapping",
      reference_book: "Illustrative citation",
      edition: null,
      volume: null,
      page: null,
      source_url: null,
      verified: true,
      scholars: scholarYahya,
    },
  ],
  "sahl-ibn-sad": [
    {
      id: 2,
      narrator_id: 3,
      scholar_id: scholarIbnHajar.id,
      original_term: "صحابي",
      normalized_term: "companion",
      explanation: "Identified as a Companion in later biographical summaries.",
      display_score: 90,
      mapping_method: "editorial display mapping",
      reference_book: "Taqrib",
      edition: null,
      volume: null,
      page: null,
      source_url: null,
      verified: true,
      scholars: scholarIbnHajar,
    },
  ],
};

export function searchFallback(filters: {
  q?: string;
  bookId?: string;
  hadithStatus?: string;
  chainStatus?: string;
  narrationStatus?: string;
  scholarId?: string;
  assessment?: string;
  page?: number;
}) {
  const page = Math.max(1, filters.page ?? 1);
  const q = (filters.q ?? "").trim().toLowerCase();
  let rows = FALLBACK_HADITHS.map((hadith) => ({
    hadith,
    variations: FALLBACK_VARIATIONS[hadith.slug] ?? [],
  }));

  if (q) {
    rows = rows.filter(({ hadith, variations }) => {
      const blob = [
        hadith.title,
        hadith.slug,
        hadith.summary,
        ...variations.flatMap((v) => [v.english_text, v.arabic_text, v.hadith_number, v.books?.title]),
      ]
        .join(" ")
        .toLowerCase();
      return blob.includes(q);
    });
  }
  if (filters.bookId) {
    const bookId = Number(filters.bookId);
    rows = rows.filter(({ variations }) => variations.some((v) => v.book_id === bookId));
  }
  if (filters.hadithStatus) {
    rows = rows.filter(({ variations }) => variations.some((v) => v.hadith_status === filters.hadithStatus));
  }
  if (filters.chainStatus) {
    rows = rows.filter(({ variations }) => variations.some((v) => v.chain_status === filters.chainStatus));
  }
  if (filters.narrationStatus) {
    rows = rows.filter(({ variations }) =>
      variations.some((v) => v.narration_status.includes(filters.narrationStatus!)),
    );
  }
  if (filters.scholarId) {
    const scholarId = Number(filters.scholarId);
    rows = rows.filter(({ variations }) =>
      variations.some((v) => v.hadith_assessments.some((a) => a.scholar_id === scholarId)),
    );
  }
  if (filters.assessment) {
    const term = filters.assessment.toLowerCase();
    rows = rows.filter(({ variations }) =>
      variations.some((v) =>
        v.hadith_assessments.some(
          (a) => a.original_grade.toLowerCase().includes(term) || (a.normalized_grade ?? "").includes(term),
        ),
      ),
    );
  }

  const total = rows.length;
  const pageSize = 12;
  const start = (page - 1) * pageSize;
  return {
    hadiths: rows.slice(start, start + pageSize).map((row) => row.hadith),
    total,
    page,
    pageSize,
    error: null as string | null,
  };
}
